### PR TITLE
Include netinet headers

### LINKED ISSUE #1: TCP_NODELAY undeclared with C++/Linux
Compiling with `g++` or `clang++` on Ubuntu 18.04 results in the following error:

```
include/swrap.h: In function ‘int swrapSocket(int, int, char, const char*, const char*)’:
include/swrap.h:171:43: error: ‘TCP_NODELAY’ was not declared in this scope
             setsockopt(sock, IPPROTO_TCP, TCP_NODELAY, (void*)&nodelay, sizeof(nodelay));
```

### PR DESCRIPTION
**Pull request by ghost**
See here: https://linux.die.net/man/7/tcp
Fixes #1

### CODE REVIEW

**Comment by BareRose** [comment]
You fixed your own issue, neat!

There is a possibility some obscure linux distro doesn't define the netinet headers and instead has everything in socket.h but for now I'm merging this. Can always add another check for that if it becomes an issue.

**Comment by ghost** [comment]
I was thinking the same thing. But, Emscripten defines those headers and I'm assuming MacOS does too, so it probably won't be an issue. As for embedded systems, I don't know.

**Comment by ghost** [comment]
Been playing around with microcontroller stuff and found that lwIP does not have netinet, it's all in socket.h as you said. So, juggling support for Ubuntu, Mac, Windows, and embedded (try NuttX maybe) is the grand challenge.

**Comment by BareRose** [comment]
What do you think about wrapping the netinet include stuff in a "ifndef TCP_NODELAY"?

That way any distros that define TCP_NODELAY in their socket.h header don't need the include, thus allowing the library to work on platforms that have everything in socket.h.

Pretty dirty, but platform detection usually is, especially when it comes to telling apart different obscure/embedded UNIX OSs.

**Comment by ghost** [comment]
True, platform detection is dirty. I think netinet might be a Linux thing that is only supposed to be available in Linux, but I don't know anything and I don't see any problem with this solution. If there is no TCP_NODELAY and there is no netinet, I suppose the system is screwed anyways. I like it!

**Pull request merged**
